server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # CoreDNS internal resolver
        resolver 10.96.0.10 valid=30s; 
        
        # Kubernetes Full DNS Name use karein: <service-name>.<namespace>.svc.cluster.local
        proxy_pass http://taskify-backend-service.taskify.svc.cluster.local:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
