apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-backend
  namespace: taskify
  labels:
    app: taskify-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskify-backend
  template:
    metadata:
      labels:
        app: taskify-backend
    spec:
      containers:
      - name: backend
        image: thesanketpawar/taskify-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/taskify"
        envFrom:
        - configMapRef:
            name: taskify-configmap
        - secretRef:
            name: taskify-secrets
